### ISSUE TITLE
Small fix for for_pupils__statistcs_basic__dice_examples_EN.ipynb

### ISSUE THREAD

**Issue by katilp** [a-monsch/HiggsSearch__P4_and_Masterclass#2]
In for_pupils__statistcs_basic__dice_examples_EN.ipynb
change normierung -> normalisation in code cell 13 (after the standard deviation equations)

Thanks!

**Comment by a-monsch** [comment]
Fixed it in [6fd9ff1](https://github.com/a-monsch/HiggsSearch__P4_and_Masterclass/commit/6fd9ff1dc5df63b7c9ccd56202e0f79e79dad1c9). The same is done in the MyBinder (`...EN_remote.ipynb`) version.
