### ISSUE TITLE
MyBinder does not find numpy

### ISSUE THREAD

**Issue by ntiltmann** [a-monsch/HiggsSearch__P4_and_Masterclass#4]
I can't start the application with the given mybinder link anymore. It seems like that there is not the right version of numpy available. The starting process crashes after this error message.
<img width="1100" alt="binder_error" src="https://user-images.githubusercontent.com/73590706/178311087-ddb4dcd1-d31a-4199-867a-50be2f1885fc.png">

**Comment by a-monsch** [comment]
MyBinder seems not have the more recent Numpy versions I have adjusted the requierements accordingly, thank you very much.
